// ---------------------------------------------------------------------------
// imc_tile_top.v
//
// Chip-level top for Zedboard. Wraps imc_core with a VIO (control + result
// readback) and an ILA (waveform capture). No PS, no AXI -- per assignment.
//
// The VIO and ILA IPs (vio_0 / ila_0) are generated by Vivado from
// `vivado/build.tcl`. In simulation use `imc_core` directly (testbench
// `sim/tb_imc_tile.sv`).
//
// Pinout (see constraints/zedboard.xdc):
//   clk_in   - 100 MHz Zedboard system clock (Y9 by default)
//   led      - mirrors `done` for visual confirmation
// ---------------------------------------------------------------------------
`timescale 1ns / 1ps

module imc_tile_top (
    input        clk_in,
    output       led
);

    // ----------------------------------------------------
    // Clock + reset
    // ----------------------------------------------------
    wire clk = clk_in;

    // Synchronous power-on reset: hold reset for 16 cycles after power-up.
    reg [3:0] rst_cnt = 4'd0;
    reg       rst_n   = 1'b0;
    always @(posedge clk) begin
        if (rst_cnt != 4'd15) begin
            rst_cnt <= rst_cnt + 4'd1;
            rst_n   <= 1'b0;
        end else begin
            rst_n <= 1'b1;
        end
    end

    // ----------------------------------------------------
    // VIO control / status
    //   Outputs from VIO -> design: start, soft_rst, y_rd_addr
    //   Inputs from design -> VIO : done, y_rd_data, dbg_state, dbg_i, dbg_j
    // ----------------------------------------------------
    wire        vio_start;
    wire        vio_soft_rst;
    wire [2:0]  vio_y_rd_addr;
    wire        core_done;
    wire [127:0] core_y_rd_data;
    wire [3:0]  dbg_state;
    wire [2:0]  dbg_i;
    wire [3:0]  dbg_j;
    wire [127:0] dbg_w_col;
    wire [127:0] dbg_x_row;
    wire signed [31:0] dbg_acc;
    wire signed [7:0]  dbg_y_byte;

    wire core_rst_n = rst_n & ~vio_soft_rst;

    // ----------------------------------------------------
    // VIO instance (vio_0). Generated by build.tcl with:
    //   probe_in0[0]  : done
    //   probe_in1[127:0]: y_rd_data
    //   probe_in2[3:0]: dbg_state
    //   probe_in3[2:0]: dbg_i
    //   probe_in4[3:0]: dbg_j
    //   probe_out0[0] : start
    //   probe_out1[0] : soft_rst
    //   probe_out2[2:0]: y_rd_addr
    // ----------------------------------------------------
    vio_0 u_vio (
        .clk        (clk),
        .probe_in0  (core_done),
        .probe_in1  (core_y_rd_data),
        .probe_in2  (dbg_state),
        .probe_in3  (dbg_i),
        .probe_in4  (dbg_j),
        .probe_out0 (vio_start),
        .probe_out1 (vio_soft_rst),
        .probe_out2 (vio_y_rd_addr)
    );

    // ----------------------------------------------------
    // ILA instance (ila_0). Probes:
    //   probe0  : dbg_state[3:0]
    //   probe1  : dbg_i[2:0]
    //   probe2  : dbg_j[3:0]
    //   probe3  : dbg_w_col[127:0]
    //   probe4  : dbg_x_row[127:0]
    //   probe5  : dbg_acc[31:0]
    //   probe6  : dbg_y_byte[7:0]
    //   probe7  : core_done
    // Trigger suggestion: dbg_state == 4'd5 (S_MAC1, first cycle of pipelined MAC).
    // ----------------------------------------------------
    ila_0 u_ila (
        .clk    (clk),
        .probe0 (dbg_state),
        .probe1 (dbg_i),
        .probe2 (dbg_j),
        .probe3 (dbg_w_col),
        .probe4 (dbg_x_row),
        .probe5 (dbg_acc),
        .probe6 (dbg_y_byte),
        .probe7 (core_done)
    );

    // ----------------------------------------------------
    // Core
    // ----------------------------------------------------
    imc_core u_core (
        .clk       (clk),
        .rst_n     (core_rst_n),
        .start     (vio_start),
        .done      (core_done),
        .y_rd_addr (vio_y_rd_addr),
        .y_rd_data (core_y_rd_data),
        .dbg_state (dbg_state),
        .dbg_i     (dbg_i),
        .dbg_j     (dbg_j),
        .dbg_w_col (dbg_w_col),
        .dbg_x_row (dbg_x_row),
        .dbg_acc   (dbg_acc),
        .dbg_y_byte(dbg_y_byte)
    );

    assign led = core_done;

endmodule
